import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Bath, BedDouble, CarFront, Check, ChevronLeft, ChevronRight, MapPin, Maximize2 } from "lucide-react";
import { useState } from "react";
import { ContactForm } from "@/components/kaivra/ContactForm";
import { PublicSiteHeader } from "@/components/kaivra/PublicSiteHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { supabase } from "@/integrations/supabase/client";
import { FALLBACK_PROPERTY_IMAGE, mediaSrc } from "@/lib/media";
import { listingCover, listingFeatures, listingLocation, listingPrice, titleCase, type PropertyListing } from "@/lib/property-listings";

const SITE = "https://kaivraa.com";
const queryFields = "id,title,slug,property_type,listing_type,location,city,state,country,short_description,description,price,price_display_text,currency,size_value,size_unit,bedrooms,bathrooms,parking_spaces,property_status,listing_status,featured,developer_name,latitude,longitude,key_features,published_at,created_at,updated_at,property_listing_images(id,listing_id,url,caption,sort_order,is_cover,created_at)";
export const Route = createFileRoute("/properties/$slug")({
  loader: async ({ params }) => { const { data, error } = await supabase.from("property_listings").select(queryFields).eq("slug", params.slug).eq("listing_status", "published").in("property_status", ["available", "coming_soon"]).maybeSingle(); if(error) throw error; if(!data) throw notFound(); return { listing: data as PropertyListing }; },
  head: ({ params, loaderData }) => { const listing = loaderData?.listing; const title = listing ? `${listing.title} | KAIVRA Property Listings` : "Property unavailable | KAIVRA"; const description = listing?.short_description || listing?.description?.slice(0,155) || "This KAIVRA property listing is unavailable."; const image = listing ? mediaSrc(listingCover(listing)) : null; const absolute = image?.startsWith("https://") ? image : null; return { meta: [{ title }, { name:"description",content:description }, { property:"og:title",content:title }, { property:"og:description",content:description }, { property:"og:type",content:"product" }, { property:"og:url",content:`${SITE}/properties/${params.slug}` }, { name:"twitter:card",content:"summary_large_image" }, ...(absolute ? [{ property:"og:image",content:absolute }, { name:"twitter:image",content:absolute }] : [])], links:[{rel:"canonical",href:`${SITE}/properties/${params.slug}`}], }; },
  component: PropertyDetail,
  notFoundComponent: PropertyUnavailable,
});
function PropertyUnavailable(){return <div className="flex min-h-screen flex-col items-center justify-center gap-4 px-5 text-center"><h1 className="font-display text-4xl">Property unavailable</h1><p className="text-muted-foreground">This listing is not currently available to the public.</p><Button asChild><Link to="/properties">View current listings</Link></Button></div>}
function PropertyDetail() {
  const { slug } = Route.useParams(); const [photo, setPhoto] = useState(0);
  const query = useQuery({ queryKey:["property-listing",slug], queryFn: async()=>{ const { data,error }=await supabase.from("property_listings").select(queryFields).eq("slug",slug).eq("listing_status","published").in("property_status",["available","coming_soon"]).maybeSingle(); if(error) throw error; return data as PropertyListing|null; }, initialData: Route.useLoaderData().listing });
  if (query.isLoading) return <div className="mx-auto max-w-7xl p-6"><Skeleton className="h-[32rem] w-full" /></div>;
  const listing=query.data; if(!listing) return <div className="flex min-h-screen flex-col items-center justify-center gap-4 px-5 text-center"><h1 className="font-display text-4xl">Property unavailable</h1><p className="text-muted-foreground">This listing is not currently available to the public.</p><Button asChild><Link to="/properties">View current listings</Link></Button></div>;
  const images=[...(listing.property_listing_images??[])].sort((a,b)=>a.sort_order-b.sort_order); const active=mediaSrc(images[photo]?.url ?? listingCover(listing),FALLBACK_PROPERTY_IMAGE); const features=listingFeatures(listing.key_features);
  const facts=[listing.bedrooms!=null?{icon:BedDouble,label:`${listing.bedrooms} bedrooms`}:null,listing.bathrooms!=null?{icon:Bath,label:`${listing.bathrooms} bathrooms`}:null,listing.parking_spaces!=null?{icon:CarFront,label:`${listing.parking_spaces} parking`}:null,listing.size_value!=null?{icon:Maximize2,label:`${listing.size_value} ${listing.size_unit??""}`}:null].filter(Boolean) as {icon:typeof BedDouble,label:string}[];
  return <div className="min-h-screen bg-background"><PublicSiteHeader /><main className="mx-auto w-full max-w-7xl px-5 py-7 sm:px-8"><Button asChild variant="ghost" className="mb-4"><Link to="/properties"><ChevronLeft className="mr-1 size-4" /> Property listings</Link></Button><div className="grid gap-8 lg:grid-cols-[minmax(0,1.65fr)_minmax(19rem,.85fr)]"><div><div className="relative aspect-[16/10] overflow-hidden rounded-lg bg-muted"><img src={active} alt={images[photo]?.caption||listing.title} className="size-full object-cover" />{images.length>1?<><Button size="icon" variant="secondary" aria-label="Previous photo" className="absolute left-3 top-1/2 -translate-y-1/2" onClick={()=>setPhoto((photo-1+images.length)%images.length)}><ChevronLeft /></Button><Button size="icon" variant="secondary" aria-label="Next photo" className="absolute right-3 top-1/2 -translate-y-1/2" onClick={()=>setPhoto((photo+1)%images.length)}><ChevronRight /></Button></>:null}</div>{images.length>1?<div className="mt-3 grid grid-cols-5 gap-2">{images.slice(0,10).map((image,index)=><button key={image.id} type="button" onClick={()=>setPhoto(index)} aria-label={`View photo ${index+1}`} className={`aspect-[4/3] overflow-hidden rounded-md border-2 ${photo===index?"border-primary":"border-transparent"}`}><img src={mediaSrc(image.url)} alt={image.caption||""} className="size-full object-cover" /></button>)}</div>:null}
    <section className="mt-9"><p className="eyebrow text-primary">Property description</p><p className="mt-4 whitespace-pre-line leading-7 text-muted-foreground">{listing.description}</p>{features.length?<><h2 className="mt-9 font-display text-3xl">Key features</h2><ul className="mt-4 grid gap-3 sm:grid-cols-2">{features.map((feature)=><li key={feature} className="flex gap-2 text-sm"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-success text-success-foreground"><Check className="size-3" /></span>{feature}</li>)}</ul></>:null}</section>
    <section id="enquiry" className="mt-10 border-t border-border pt-9"><p className="eyebrow text-primary">Interested in this property?</p><h2 className="mt-2 font-display text-3xl">Enquire about this property</h2><p className="mb-6 mt-2 text-sm text-muted-foreground">Tell us how we can help and a KAIVRA adviser will respond.</p><ContactForm initialSubject={`Property enquiry — ${listing.title}`} initialMessage={`I would like more information about ${listing.title} (${listing.slug}).`} hideReturnHome /></section></div>
    <aside className="lg:sticky lg:top-24 lg:self-start"><div className="border-y border-border py-6 lg:rounded-lg lg:border lg:bg-card lg:p-6 lg:shadow-card"><div className="flex flex-wrap gap-2"><Badge>For {titleCase(listing.listing_type)}</Badge><Badge variant="outline">{titleCase(listing.property_status)}</Badge></div><h1 className="mt-4 font-display text-4xl">{listing.title}</h1><p className="mt-2 flex gap-1.5 text-sm text-muted-foreground"><MapPin className="size-4 shrink-0" />{listingLocation(listing)}</p><p className="mt-5 text-3xl font-semibold text-primary">{listingPrice(listing)}</p>{facts.length?<div className="mt-6 grid grid-cols-2 gap-4 border-y border-border py-5">{facts.map(({icon:Icon,label})=><div key={label} className="flex items-center gap-2 text-sm"><Icon className="size-5 text-primary" />{label}</div>)}</div>:null}<Button asChild size="lg" className="mt-6 w-full"><a href="#enquiry">Enquire about this property</a></Button><dl className="mt-6 grid grid-cols-2 gap-x-4 gap-y-3 text-sm"><dt className="text-muted-foreground">Property type</dt><dd>{titleCase(listing.property_type)}</dd><dt className="text-muted-foreground">Listing type</dt><dd>For {titleCase(listing.listing_type)}</dd>{listing.developer_name?<><dt className="text-muted-foreground">Developer</dt><dd>{listing.developer_name}</dd></>:null}</dl></div></aside></div></main></div>;
}
