/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RealEstateInvestmentAbujaRouteImport } from './routes/real-estate-investment-abuja'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthenticatedApplicationRouteImport } from './routes/_authenticated/application'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin.access'
import { Route as AuthenticatedAdminAdvisersRouteImport } from './routes/_authenticated/admin.advisers'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminCorrectionsRouteImport } from './routes/_authenticated/admin.corrections'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminInspectionsRouteImport } from './routes/_authenticated/admin.inspections'
import { Route as AuthenticatedAdminInvestorsRouteImport } from './routes/_authenticated/admin.investors'
import { Route as AuthenticatedAdminPaymentAccountsRouteImport } from './routes/_authenticated/admin.payment-accounts'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin.transactions'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications.index'
import { Route as AuthenticatedApplicationsAppIdRouteImport } from './routes/_authenticated/applications.$appId'
import { Route as AuthenticatedInspectionsIndexRouteImport } from './routes/_authenticated/inspections.index'
import { Route as AuthenticatedInspectionsNewRouteImport } from './routes/_authenticated/inspections.new'
import { Route as ApiPublicAiChatRouteImport } from './routes/api/public/ai-chat'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicDocumentUrlRouteImport } from './routes/api/public/document-url'
import { Route as ApiPublicEmailCronRouteImport } from './routes/api/public/email-cron'
import { Route as ApiPublicPassportAvatarsRouteImport } from './routes/api/public/passport-avatars'
import { Route as ApiPublicPaymentAccountNumberRouteImport } from './routes/api/public/payment-account-number'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as AuthenticatedAdminApplicationsIndexRouteImport } from './routes/_authenticated/admin.applications.index'
import { Route as AuthenticatedAdminApplicationsAppIdRouteImport } from './routes/_authenticated/admin.applications.$appId'
import { Route as ApiPublicAvatarSplatRouteImport } from './routes/api/public/avatar.$'
import { Route as ApiPublicProjectImageSplatRouteImport } from './routes/api/public/project-image.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateInvestmentAbujaRoute =
  RealEstateInvestmentAbujaRouteImport.update({
    id: '/real-estate-investment-abuja',
    path: '/real-estate-investment-abuja',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationRoute =
  AuthenticatedApplicationRouteImport.update({
    id: '/application',
    path: '/application',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/admin/access',
    path: '/admin/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdvisersRoute =
  AuthenticatedAdminAdvisersRouteImport.update({
    id: '/admin/advisers',
    path: '/admin/advisers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCorrectionsRoute =
  AuthenticatedAdminCorrectionsRouteImport.update({
    id: '/admin/corrections',
    path: '/admin/corrections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/admin/emails',
    path: '/admin/emails',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/admin/enquiries',
    path: '/admin/enquiries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInspectionsRoute =
  AuthenticatedAdminInspectionsRouteImport.update({
    id: '/admin/inspections',
    path: '/admin/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvestorsRoute =
  AuthenticatedAdminInvestorsRouteImport.update({
    id: '/admin/investors',
    path: '/admin/investors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentAccountsRoute =
  AuthenticatedAdminPaymentAccountsRouteImport.update({
    id: '/admin/payment-accounts',
    path: '/admin/payment-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/admin/projects',
    path: '/admin/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/admin/transactions',
    path: '/admin/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsAppIdRoute =
  AuthenticatedApplicationsAppIdRouteImport.update({
    id: '/applications/$appId',
    path: '/applications/$appId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionsIndexRoute =
  AuthenticatedInspectionsIndexRouteImport.update({
    id: '/inspections/',
    path: '/inspections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionsNewRoute =
  AuthenticatedInspectionsNewRouteImport.update({
    id: '/inspections/new',
    path: '/inspections/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAiChatRoute = ApiPublicAiChatRouteImport.update({
  id: '/api/public/ai-chat',
  path: '/api/public/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDocumentUrlRoute = ApiPublicDocumentUrlRouteImport.update({
  id: '/api/public/document-url',
  path: '/api/public/document-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailCronRoute = ApiPublicEmailCronRouteImport.update({
  id: '/api/public/email-cron',
  path: '/api/public/email-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPassportAvatarsRoute =
  ApiPublicPassportAvatarsRouteImport.update({
    id: '/api/public/passport-avatars',
    path: '/api/public/passport-avatars',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentAccountNumberRoute =
  ApiPublicPaymentAccountNumberRouteImport.update({
    id: '/api/public/payment-account-number',
    path: '/api/public/payment-account-number',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminApplicationsIndexRoute =
  AuthenticatedAdminApplicationsIndexRouteImport.update({
    id: '/admin/applications/',
    path: '/admin/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApplicationsAppIdRoute =
  AuthenticatedAdminApplicationsAppIdRouteImport.update({
    id: '/admin/applications/$appId',
    path: '/admin/applications/$appId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAvatarSplatRoute = ApiPublicAvatarSplatRouteImport.update({
  id: '/api/public/avatar/$',
  path: '/api/public/avatar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjectImageSplatRoute =
  ApiPublicProjectImageSplatRouteImport.update({
    id: '/api/public/project-image/$',
    path: '/api/public/project-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/real-estate-investment-abuja': typeof RealEstateInvestmentAbujaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/application': typeof AuthenticatedApplicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/advisers': typeof AuthenticatedAdminAdvisersRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/corrections': typeof AuthenticatedAdminCorrectionsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/inspections': typeof AuthenticatedAdminInspectionsRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/payment-accounts': typeof AuthenticatedAdminPaymentAccountsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/applications/$appId': typeof AuthenticatedApplicationsAppIdRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/document-url': typeof ApiPublicDocumentUrlRoute
  '/api/public/email-cron': typeof ApiPublicEmailCronRoute
  '/api/public/passport-avatars': typeof ApiPublicPassportAvatarsRoute
  '/api/public/payment-account-number': typeof ApiPublicPaymentAccountNumberRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/admin/applications/$appId': typeof AuthenticatedAdminApplicationsAppIdRoute
  '/api/public/avatar/$': typeof ApiPublicAvatarSplatRoute
  '/api/public/project-image/$': typeof ApiPublicProjectImageSplatRoute
  '/admin/applications/': typeof AuthenticatedAdminApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/real-estate-investment-abuja': typeof RealEstateInvestmentAbujaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/application': typeof AuthenticatedApplicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/advisers': typeof AuthenticatedAdminAdvisersRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/corrections': typeof AuthenticatedAdminCorrectionsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/inspections': typeof AuthenticatedAdminInspectionsRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/payment-accounts': typeof AuthenticatedAdminPaymentAccountsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/applications/$appId': typeof AuthenticatedApplicationsAppIdRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/document-url': typeof ApiPublicDocumentUrlRoute
  '/api/public/email-cron': typeof ApiPublicEmailCronRoute
  '/api/public/passport-avatars': typeof ApiPublicPassportAvatarsRoute
  '/api/public/payment-account-number': typeof ApiPublicPaymentAccountNumberRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/inspections': typeof AuthenticatedInspectionsIndexRoute
  '/admin/applications/$appId': typeof AuthenticatedAdminApplicationsAppIdRoute
  '/api/public/avatar/$': typeof ApiPublicAvatarSplatRoute
  '/api/public/project-image/$': typeof ApiPublicProjectImageSplatRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/real-estate-investment-abuja': typeof RealEstateInvestmentAbujaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/application': typeof AuthenticatedApplicationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/advisers': typeof AuthenticatedAdminAdvisersRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/corrections': typeof AuthenticatedAdminCorrectionsRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/inspections': typeof AuthenticatedAdminInspectionsRoute
  '/_authenticated/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/_authenticated/admin/payment-accounts': typeof AuthenticatedAdminPaymentAccountsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/applications/$appId': typeof AuthenticatedApplicationsAppIdRoute
  '/_authenticated/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/api/public/ai-chat': typeof ApiPublicAiChatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/document-url': typeof ApiPublicDocumentUrlRoute
  '/api/public/email-cron': typeof ApiPublicEmailCronRoute
  '/api/public/passport-avatars': typeof ApiPublicPassportAvatarsRoute
  '/api/public/payment-account-number': typeof ApiPublicPaymentAccountNumberRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/_authenticated/admin/applications/$appId': typeof AuthenticatedAdminApplicationsAppIdRoute
  '/api/public/avatar/$': typeof ApiPublicAvatarSplatRoute
  '/api/public/project-image/$': typeof ApiPublicProjectImageSplatRoute
  '/_authenticated/admin/applications/': typeof AuthenticatedAdminApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/real-estate-investment-abuja'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/application'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/profile'
    | '/transactions'
    | '/projects/$projectId'
    | '/projects/'
    | '/admin/access'
    | '/admin/advisers'
    | '/admin/analytics'
    | '/admin/corrections'
    | '/admin/emails'
    | '/admin/enquiries'
    | '/admin/inspections'
    | '/admin/investors'
    | '/admin/payment-accounts'
    | '/admin/projects'
    | '/admin/support'
    | '/admin/transactions'
    | '/applications/$appId'
    | '/inspections/new'
    | '/api/public/ai-chat'
    | '/api/public/contact'
    | '/api/public/document-url'
    | '/api/public/email-cron'
    | '/api/public/passport-avatars'
    | '/api/public/payment-account-number'
    | '/api/public/track'
    | '/admin/'
    | '/applications/'
    | '/inspections/'
    | '/admin/applications/$appId'
    | '/api/public/avatar/$'
    | '/api/public/project-image/$'
    | '/admin/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/real-estate-investment-abuja'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/application'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/profile'
    | '/transactions'
    | '/projects/$projectId'
    | '/projects'
    | '/admin/access'
    | '/admin/advisers'
    | '/admin/analytics'
    | '/admin/corrections'
    | '/admin/emails'
    | '/admin/enquiries'
    | '/admin/inspections'
    | '/admin/investors'
    | '/admin/payment-accounts'
    | '/admin/projects'
    | '/admin/support'
    | '/admin/transactions'
    | '/applications/$appId'
    | '/inspections/new'
    | '/api/public/ai-chat'
    | '/api/public/contact'
    | '/api/public/document-url'
    | '/api/public/email-cron'
    | '/api/public/passport-avatars'
    | '/api/public/payment-account-number'
    | '/api/public/track'
    | '/admin'
    | '/applications'
    | '/inspections'
    | '/admin/applications/$appId'
    | '/api/public/avatar/$'
    | '/api/public/project-image/$'
    | '/admin/applications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/real-estate-investment-abuja'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/_authenticated/application'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/transactions'
    | '/projects/$projectId'
    | '/projects/'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/advisers'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/corrections'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/inspections'
    | '/_authenticated/admin/investors'
    | '/_authenticated/admin/payment-accounts'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/applications/$appId'
    | '/_authenticated/inspections/new'
    | '/api/public/ai-chat'
    | '/api/public/contact'
    | '/api/public/document-url'
    | '/api/public/email-cron'
    | '/api/public/passport-avatars'
    | '/api/public/payment-account-number'
    | '/api/public/track'
    | '/_authenticated/admin/'
    | '/_authenticated/applications/'
    | '/_authenticated/inspections/'
    | '/_authenticated/admin/applications/$appId'
    | '/api/public/avatar/$'
    | '/api/public/project-image/$'
    | '/_authenticated/admin/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RealEstateInvestmentAbujaRoute: typeof RealEstateInvestmentAbujaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicAiChatRoute: typeof ApiPublicAiChatRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicDocumentUrlRoute: typeof ApiPublicDocumentUrlRoute
  ApiPublicEmailCronRoute: typeof ApiPublicEmailCronRoute
  ApiPublicPassportAvatarsRoute: typeof ApiPublicPassportAvatarsRoute
  ApiPublicPaymentAccountNumberRoute: typeof ApiPublicPaymentAccountNumberRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicAvatarSplatRoute: typeof ApiPublicAvatarSplatRoute
  ApiPublicProjectImageSplatRoute: typeof ApiPublicProjectImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate-investment-abuja': {
      id: '/real-estate-investment-abuja'
      path: '/real-estate-investment-abuja'
      fullPath: '/real-estate-investment-abuja'
      preLoaderRoute: typeof RealEstateInvestmentAbujaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/application': {
      id: '/_authenticated/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof AuthenticatedApplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/advisers': {
      id: '/_authenticated/admin/advisers'
      path: '/admin/advisers'
      fullPath: '/admin/advisers'
      preLoaderRoute: typeof AuthenticatedAdminAdvisersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/corrections': {
      id: '/_authenticated/admin/corrections'
      path: '/admin/corrections'
      fullPath: '/admin/corrections'
      preLoaderRoute: typeof AuthenticatedAdminCorrectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/inspections': {
      id: '/_authenticated/admin/inspections'
      path: '/admin/inspections'
      fullPath: '/admin/inspections'
      preLoaderRoute: typeof AuthenticatedAdminInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/investors': {
      id: '/_authenticated/admin/investors'
      path: '/admin/investors'
      fullPath: '/admin/investors'
      preLoaderRoute: typeof AuthenticatedAdminInvestorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payment-accounts': {
      id: '/_authenticated/admin/payment-accounts'
      path: '/admin/payment-accounts'
      fullPath: '/admin/payment-accounts'
      preLoaderRoute: typeof AuthenticatedAdminPaymentAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/$appId': {
      id: '/_authenticated/applications/$appId'
      path: '/applications/$appId'
      fullPath: '/applications/$appId'
      preLoaderRoute: typeof AuthenticatedApplicationsAppIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections/': {
      id: '/_authenticated/inspections/'
      path: '/inspections'
      fullPath: '/inspections/'
      preLoaderRoute: typeof AuthenticatedInspectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections/new': {
      id: '/_authenticated/inspections/new'
      path: '/inspections/new'
      fullPath: '/inspections/new'
      preLoaderRoute: typeof AuthenticatedInspectionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ai-chat': {
      id: '/api/public/ai-chat'
      path: '/api/public/ai-chat'
      fullPath: '/api/public/ai-chat'
      preLoaderRoute: typeof ApiPublicAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/document-url': {
      id: '/api/public/document-url'
      path: '/api/public/document-url'
      fullPath: '/api/public/document-url'
      preLoaderRoute: typeof ApiPublicDocumentUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-cron': {
      id: '/api/public/email-cron'
      path: '/api/public/email-cron'
      fullPath: '/api/public/email-cron'
      preLoaderRoute: typeof ApiPublicEmailCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/passport-avatars': {
      id: '/api/public/passport-avatars'
      path: '/api/public/passport-avatars'
      fullPath: '/api/public/passport-avatars'
      preLoaderRoute: typeof ApiPublicPassportAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-account-number': {
      id: '/api/public/payment-account-number'
      path: '/api/public/payment-account-number'
      fullPath: '/api/public/payment-account-number'
      preLoaderRoute: typeof ApiPublicPaymentAccountNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/applications/': {
      id: '/_authenticated/admin/applications/'
      path: '/admin/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications/$appId': {
      id: '/_authenticated/admin/applications/$appId'
      path: '/admin/applications/$appId'
      fullPath: '/admin/applications/$appId'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsAppIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/avatar/$': {
      id: '/api/public/avatar/$'
      path: '/api/public/avatar/$'
      fullPath: '/api/public/avatar/$'
      preLoaderRoute: typeof ApiPublicAvatarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/project-image/$': {
      id: '/api/public/project-image/$'
      path: '/api/public/project-image/$'
      fullPath: '/api/public/project-image/$'
      preLoaderRoute: typeof ApiPublicProjectImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationRoute: typeof AuthenticatedApplicationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminAdvisersRoute: typeof AuthenticatedAdminAdvisersRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCorrectionsRoute: typeof AuthenticatedAdminCorrectionsRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminInspectionsRoute: typeof AuthenticatedAdminInspectionsRoute
  AuthenticatedAdminInvestorsRoute: typeof AuthenticatedAdminInvestorsRoute
  AuthenticatedAdminPaymentAccountsRoute: typeof AuthenticatedAdminPaymentAccountsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedApplicationsAppIdRoute: typeof AuthenticatedApplicationsAppIdRoute
  AuthenticatedInspectionsNewRoute: typeof AuthenticatedInspectionsNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedInspectionsIndexRoute: typeof AuthenticatedInspectionsIndexRoute
  AuthenticatedAdminApplicationsAppIdRoute: typeof AuthenticatedAdminApplicationsAppIdRoute
  AuthenticatedAdminApplicationsIndexRoute: typeof AuthenticatedAdminApplicationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationRoute: AuthenticatedApplicationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminAdvisersRoute: AuthenticatedAdminAdvisersRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCorrectionsRoute: AuthenticatedAdminCorrectionsRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminInspectionsRoute: AuthenticatedAdminInspectionsRoute,
  AuthenticatedAdminInvestorsRoute: AuthenticatedAdminInvestorsRoute,
  AuthenticatedAdminPaymentAccountsRoute:
    AuthenticatedAdminPaymentAccountsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
  AuthenticatedApplicationsAppIdRoute: AuthenticatedApplicationsAppIdRoute,
  AuthenticatedInspectionsNewRoute: AuthenticatedInspectionsNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedInspectionsIndexRoute: AuthenticatedInspectionsIndexRoute,
  AuthenticatedAdminApplicationsAppIdRoute:
    AuthenticatedAdminApplicationsAppIdRoute,
  AuthenticatedAdminApplicationsIndexRoute:
    AuthenticatedAdminApplicationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RealEstateInvestmentAbujaRoute: RealEstateInvestmentAbujaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicAiChatRoute: ApiPublicAiChatRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicDocumentUrlRoute: ApiPublicDocumentUrlRoute,
  ApiPublicEmailCronRoute: ApiPublicEmailCronRoute,
  ApiPublicPassportAvatarsRoute: ApiPublicPassportAvatarsRoute,
  ApiPublicPaymentAccountNumberRoute: ApiPublicPaymentAccountNumberRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicAvatarSplatRoute: ApiPublicAvatarSplatRoute,
  ApiPublicProjectImageSplatRoute: ApiPublicProjectImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
