/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApplicationRouteImport } from './routes/_authenticated/application'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAdvisersRouteImport } from './routes/_authenticated/admin.advisers'
import { Route as AuthenticatedAdminInvestorsRouteImport } from './routes/_authenticated/admin.investors'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications.index'
import { Route as AuthenticatedApplicationsAppIdRouteImport } from './routes/_authenticated/applications.$appId'
import { Route as AuthenticatedAdminApplicationsAppIdRouteImport } from './routes/_authenticated/admin.applications.$appId'
import { Route as ApiPublicProjectImageSplatRouteImport } from './routes/api/public/project-image.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationRoute =
  AuthenticatedApplicationRouteImport.update({
    id: '/application',
    path: '/application',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAdvisersRoute =
  AuthenticatedAdminAdvisersRouteImport.update({
    id: '/admin/advisers',
    path: '/admin/advisers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvestorsRoute =
  AuthenticatedAdminInvestorsRouteImport.update({
    id: '/admin/investors',
    path: '/admin/investors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/admin/projects',
    path: '/admin/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsAppIdRoute =
  AuthenticatedApplicationsAppIdRouteImport.update({
    id: '/applications/$appId',
    path: '/applications/$appId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApplicationsAppIdRoute =
  AuthenticatedAdminApplicationsAppIdRouteImport.update({
    id: '/admin/applications/$appId',
    path: '/admin/applications/$appId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicProjectImageSplatRoute =
  ApiPublicProjectImageSplatRouteImport.update({
    id: '/api/public/project-image/$',
    path: '/api/public/project-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/application': typeof AuthenticatedApplicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin/advisers': typeof AuthenticatedAdminAdvisersRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/applications/$appId': typeof AuthenticatedApplicationsAppIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/admin/applications/$appId': typeof AuthenticatedAdminApplicationsAppIdRoute
  '/api/public/project-image/$': typeof ApiPublicProjectImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/application': typeof AuthenticatedApplicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin/advisers': typeof AuthenticatedAdminAdvisersRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/applications/$appId': typeof AuthenticatedApplicationsAppIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/admin/applications/$appId': typeof AuthenticatedAdminApplicationsAppIdRoute
  '/api/public/project-image/$': typeof ApiPublicProjectImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/application': typeof AuthenticatedApplicationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/_authenticated/admin/advisers': typeof AuthenticatedAdminAdvisersRoute
  '/_authenticated/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/applications/$appId': typeof AuthenticatedApplicationsAppIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/admin/applications/$appId': typeof AuthenticatedAdminApplicationsAppIdRoute
  '/api/public/project-image/$': typeof ApiPublicProjectImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/application'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/profile'
    | '/projects/$projectId'
    | '/admin/advisers'
    | '/admin/investors'
    | '/admin/projects'
    | '/applications/$appId'
    | '/admin/'
    | '/applications/'
    | '/admin/applications/$appId'
    | '/api/public/project-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/application'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/profile'
    | '/projects/$projectId'
    | '/admin/advisers'
    | '/admin/investors'
    | '/admin/projects'
    | '/applications/$appId'
    | '/admin'
    | '/applications'
    | '/admin/applications/$appId'
    | '/api/public/project-image/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/application'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/projects/$projectId'
    | '/_authenticated/admin/advisers'
    | '/_authenticated/admin/investors'
    | '/_authenticated/admin/projects'
    | '/_authenticated/applications/$appId'
    | '/_authenticated/admin/'
    | '/_authenticated/applications/'
    | '/_authenticated/admin/applications/$appId'
    | '/api/public/project-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ApiPublicProjectImageSplatRoute: typeof ApiPublicProjectImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/application': {
      id: '/_authenticated/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof AuthenticatedApplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/advisers': {
      id: '/_authenticated/admin/advisers'
      path: '/admin/advisers'
      fullPath: '/admin/advisers'
      preLoaderRoute: typeof AuthenticatedAdminAdvisersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/investors': {
      id: '/_authenticated/admin/investors'
      path: '/admin/investors'
      fullPath: '/admin/investors'
      preLoaderRoute: typeof AuthenticatedAdminInvestorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/$appId': {
      id: '/_authenticated/applications/$appId'
      path: '/applications/$appId'
      fullPath: '/applications/$appId'
      preLoaderRoute: typeof AuthenticatedApplicationsAppIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications/$appId': {
      id: '/_authenticated/admin/applications/$appId'
      path: '/admin/applications/$appId'
      fullPath: '/admin/applications/$appId'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsAppIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/project-image/$': {
      id: '/api/public/project-image/$'
      path: '/api/public/project-image/$'
      fullPath: '/api/public/project-image/$'
      preLoaderRoute: typeof ApiPublicProjectImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationRoute: typeof AuthenticatedApplicationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAdvisersRoute: typeof AuthenticatedAdminAdvisersRoute
  AuthenticatedAdminInvestorsRoute: typeof AuthenticatedAdminInvestorsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedApplicationsAppIdRoute: typeof AuthenticatedApplicationsAppIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedAdminApplicationsAppIdRoute: typeof AuthenticatedAdminApplicationsAppIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationRoute: AuthenticatedApplicationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAdvisersRoute: AuthenticatedAdminAdvisersRoute,
  AuthenticatedAdminInvestorsRoute: AuthenticatedAdminInvestorsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedApplicationsAppIdRoute: AuthenticatedApplicationsAppIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedAdminApplicationsAppIdRoute:
    AuthenticatedAdminApplicationsAppIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ApiPublicProjectImageSplatRoute: ApiPublicProjectImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
