// This file is automatically generated. Do not edit it directly.
export async function authenticateCronRequest(request: Request): Promise<Response | null> {
  const currentSecret = process.env["LOVABLE_CRON_SECRET"];
  const previousSecret = process.env["LOVABLE_CRON_SECRET_PREVIOUS"];
  const relaySecret = process.env["KAIVRA_CRON_RELAY_SECRET"];

  if (!currentSecret) {
    return new Response("Server configuration error", { status: 500 });
  }

  const match = /^Bearer ([^\s,]+)$/.exec(request.headers.get("authorization") ?? "");
  const token = match?.[1];
  if (!token) {
    return new Response("Unauthorized", { status: 401 });
  }

  const { createHash, timingSafeEqual } = await import("node:crypto");
  const digest = (value: string) => createHash("sha256").update(value, "utf8").digest();
  const providedDigest = digest(token);

  const allowedSecrets = [currentSecret, previousSecret, relaySecret].filter(
    (s): s is string => typeof s === "string" && s.length > 0
  );
  const isAuthorized = allowedSecrets.some((secret) =>
    timingSafeEqual(providedDigest, digest(secret))
  );

  if (!isAuthorized) {
    return new Response("Unauthorized", { status: 401 });
  }

  return null;
}
